// <auto-generated />
namespace Moto.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddT1isCancelledT2T1isCancelledtoLapTime : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddT1isCancelledT2T1isCancelledtoLapTime));
        
        string IMigrationMetadata.Id
        {
            get { return "202011302001052_Add T1isCancelled T2T1isCancelled ... to LapTime"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
